### ISSUE TITLE
Fetch broken on local file urls

### ISSUE THREAD

**Issue by srt19170** [d3/d3-fetch#21]
I seem to be the oddball user running a file-based d3/javascript app, but Chrome does not support fetch() on local file urls, even if --allow-file-access-from-files is set.  As a result, 5.0 broke my code that uses d3.xml() to load a local file url.  And I presume there's some subset of users who do file-based testing that might also be affected.

There's a Chromium issue open (https://bugs.chromium.org/p/chromium/issues/detail?id=810400) to address this disparity between XHR and Fetch.

**Comment by mbostock** [comment]
d3-fetch’s behavior is whatever the standard Fetch behavior is (in the current browser); D3 is not a compatibility layer. If the native Fetch API doesn’t support local file URLs, then neither does d3-fetch.

If you want to fetch local files, you could:

1. Encourage browser vendors to enable this feature, such as by voicing your support for it by filing or staring an issue (e.g., [Chrome’s issue](https://bugs.chromium.org/p/chromium/issues/detail?id=810400)).

2. Use a different native API, such as XMLHttpRequest (perhaps with [d3-request](https://github.com/d3/d3-require)).

3. Write a new library, perhaps as a wrapper around d3-fetch (or Fetch), that somehow works around the issue.

You could also consider running your own local web server so that you don’t need access to the local file system, which may be the path of least resistance. Also note that browsers allow you to read local files using `<input type=file>`; see [Reading Local Files](https://beta.observablehq.com/@mbostock/reading-local-files) for example.
